name: Metrics

on:
  # Schedule daily updates
  schedule: [ { cron: "0 5 * * 1" } ]
  # (optional) Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    name: Base metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: faylite/metrics@master
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: faylite
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Oslo

          repositories_affiliations: owner
          commits_authoring: ${{ secrets.METRICS_USERNAMES }}

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_section: recently-used, most-used
          plugin_languages_details: percentage, bytes-size

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
